/**
 * lib/leagues/champions-league.ts — clubs that enter the app THROUGH the
 * Champions League (not in any domestic league we run). Merged into ALL_CLUBS
 * so club(code) / ClubCrest resolve them everywhere. The 21 CL clubs that also
 * play in our domestic leagues keep their existing entries — they are not
 * duplicated here. GENERATED by scripts/import-champions-league.mjs.
 */
import type { Club } from "@/lib/premierLeague/clubs";

export const CHAMPIONS_LEAGUE_CLUBS: Club[] = [
  { code: "AEK", name: "AEK Athens", short: "AEK", nickname: "Dikephalos", primary: "#F1B300", city: "Athens", stadium: "OPAP Arena" },
  { code: "BOD", name: "Bodø/Glimt", short: "Bodø", nickname: "Gutan", primary: "#FFD200", city: "Bodø", stadium: "Aspmyra Stadion" },
  { code: "BRU", name: "Club Brugge", short: "Brugge", nickname: "Blauw-Zwart", primary: "#005CA9", city: "Bruges", stadium: "Jan Breydel Stadium" },
  { code: "FEN", name: "Fenerbahçe", short: "Fener", nickname: "Sarı Kanaryalar", primary: "#0A1E3F", city: "Istanbul", stadium: "Şükrü Saracoğlu Stadium" },
  { code: "FEY", name: "Feyenoord", short: "Feyenoord", nickname: "De Stadionclub", primary: "#E30613", city: "Rotterdam", stadium: "De Kuip" },
  { code: "GAL", name: "Galatasaray", short: "Galatasaray", nickname: "Cimbom", primary: "#A90432", city: "Istanbul", stadium: "Rams Park" },
  { code: "LAS", name: "LASK", short: "LASK", nickname: "Die Laskler", primary: "#1A1A1A", city: "Linz", stadium: "Raiffeisen Arena" },
  { code: "POR", name: "Porto", short: "Porto", nickname: "Dragões", primary: "#00579C", city: "Porto", stadium: "Estádio do Dragão" },
  { code: "PSV", name: "PSV Eindhoven", short: "PSV", nickname: "Boeren", primary: "#ED1C24", city: "Eindhoven", stadium: "Philips Stadion" },
  { code: "SAB", name: "Sabah", short: "Sabah", nickname: "Sabah", primary: "#00843D", city: "Baku", stadium: "Bank Respublika Arena" },
  { code: "SHK", name: "Shakhtar Donetsk", short: "Shakhtar", nickname: "Hirnyky", primary: "#F58220", city: "Donetsk", stadium: "Arena Lviv" },
  { code: "SLA", name: "Slavia Prague", short: "Slavia", nickname: "Sešívaní", primary: "#D31145", city: "Prague", stadium: "Eden Arena" },
  { code: "SLB", name: "Slovan Bratislava", short: "Slovan", nickname: "Belasí", primary: "#005BAB", city: "Bratislava", stadium: "Tehelné pole" },
  { code: "SPO", name: "Sporting CP", short: "Sporting", nickname: "Os Leões", primary: "#008057", city: "Lisbon", stadium: "Estádio José Alvalade" },
  { code: "VIK", name: "Viking", short: "Viking", nickname: "Mørke", primary: "#003DA5", city: "Stavanger", stadium: "SR-Bank Arena" },
];
